[package]
name = "shkaf"
version = "0.1.0"
edition = "2024"

[lints.clippy]
# Stylistic
self_named_module_files = "deny"
needless_return = "allow"
single_match = "allow"

# Annoying default lints
uninlined_format_args = "allow" # Inconsistency with complex format args
new_without_default = "allow"   # Not all types make sense with default

# Safety
await_holding_invalid_type = "deny"
await_holding_refcell_ref = "deny"
await_holding_lock = "deny"
disallowed_types = "deny"
disallowed_methods = "deny"

[profile.release]
codegen-units = 1
lto = "fat"

[profile.dev]
opt-level = 1
lto = "off"
codegen-units = 256
overflow-checks = false

[profile.dev.package."*"]
opt-level = 3
overflow-checks = false

[dependencies]
camino = "1.2.2"
clap = { version = "4.5.60", features = ["derive"] }
color-eyre = "0.6.5"
etcetera = "0.11.0"
fern = "0.7.1"
fs-err = "3.3.0"
handlebars = "6.4.0"
log = "0.4.29"
owo-colors = "4.3.0"
serde = { version = "1.0.228", features = ["derive"] }
smart-default = "0.7.1"
whoami = "2.1.1"
tempfile = "3.26.0"
toml = "1.0.6"
walkdir = "2.5.0"
tap = "1.0.1"
